version: '3.7'

networks:
    backend:
        driver: bridge

services:

    php-fpm:
        build:
            context: ./php-fpm
        environment:
            - TZ=${TZ}
        networks:
            - backend
        volumes:
            - ./..:/var/www
            - ./php-fpm/opcache.ini:/usr/local/etc/php/conf.d/opcache.ini
            - ./php-fpm/xdebug.ini:/usr/local/etc/php/conf.d/xdebug.ini
            - ./php-fpm/app.ini:/usr/local/etc/php/conf.d/app.ini
            - ./php-fpm/php.ini:/usr/local/etc/php/php.ini

    nginx:
        build:
            context: ./nginx
        depends_on:
            - php-fpm
        environment:
            - TZ=${TZ}
        networks:
            - backend
        ports:
            - 80:80
        volumes:
            - ./..:/var/www
            - ./nginx/conf.d:/etc/nginx/conf.d
            - ./nginx/nginx.conf:/etc/nginx/nginx.conf
            - ./logs/nginx:/var/log/nginx
